export const coffees = [
  {
    id: 1,
    types: ['Tradicional'],
    name: 'Expresso Tradicional',
    price: 9.9,
    description: 'O tradicional café feito com água quente e grãos moídos',
    image: 'expresso.png',
    quantity: 0,
  },
  {
    id: 2,
    types: ['Tradicional'],
    name: 'Expresso Americano',
    price: 10.9,
    description: 'Expresso diluído, menos intenso que o tradicional',
    image: 'americano.png',
    quantity: 0,
  },
  {
    id: 3,
    types: ['Tradicional'],
    name: 'Expresso Cremoso',
    price: 12.9,
    description: 'Café expresso tradicional com espuma cremosa',
    image: 'expressocremoso.png',
    quantity: 0,
  },
  {
    id: 4,
    types: ['Tradicional', 'Gelado'],
    name: 'Expresso Gelado',
    price: 12.9,
    description: 'Bebida preparada com café expresso e cubos de gelo',
    image: 'expressogelado.png',
    quantity: 0,
  },
  {
    id: 5,
    types: ['Tradicional', 'Com Leite'],
    name: 'Café com Leite',
    price: 12.9,
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    image: 'cafecomleite.png',
    quantity: 0,
  },
  {
    id: 6,
    types: ['Tradicional', 'Com Leite'],
    name: 'Latte',
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    price: 14.9,
    image: 'latte.png',
    quantity: 0,
  },
  {
    id: 7,
    types: ['Tradicional', 'Com Leite'],
    name: 'Cappuccino',
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    price: 14.9,
    image: 'capuccino.png',
    quantity: 0,
  },
  {
    id: 8,
    types: ['Tradicional', 'Com Leite'],
    name: 'Macchiato',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    price: 14.9,
    image: 'macchiato.png',
    quantity: 0,
  },
  {
    id: 9,
    types: ['Tradicional', 'Com Leite'],
    name: 'Mocaccino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: 15.9,
    image: 'mocaccino.png',
    quantity: 0,
  },
  {
    id: 10,
    types: ['Especial', 'Com Leite'],
    name: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: 19.9,
    image: 'chocolatequente.png',
    quantity: 0,
  },
  {
    id: 11,
    types: ['Especial', 'Alcoólico'],
    name: 'Cubano',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: 19.9,
    image: 'cubano.png',
    quantity: 0,
  },
  {
    id: 12,
    types: ['Especial'],
    name: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    price: 19.9,
    image: 'havaiano.png',
    quantity: 0,
  },
  {
    id: 13,
    types: ['Especial'],
    name: 'Árabe',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    price: 21.9,
    image: 'arabe.png',
    quantity: 0,
  },
  {
    id: 14,
    types: ['Especial', 'Alcoólico'],
    name: 'Irlandês',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    price: 25,
    image: 'irlandes.png',
    quantity: 0,
  },
]
